services:
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app:delegated
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run start:dev"
